### ISSUE TITLE
MuZero Implementation

### ISSUE THREAD

**Issue by sbodenstein** [deepmind/open_spiel#135] opened 2020-01-17 14:25 UTC
A natural extension of AlphaZero is [MuZero](https://arxiv.org/abs/1911.08265). The pseudocode implementation is very similar to that of AlphaZero, so it would be interesting to extend the AlphaZero implementation #134 to also support MuZero.

Is there any interest in having a MuZero implementation in OpenSpiel?

**Comment by hejujie** [comment] 2020-02-15 21:19
I also think this work is very interesting, and I will start it in next week, maybe it will be finished in this month if I am not busy.

**Comment by hejujie** [comment] 2020-02-19 11:46
Some issue about reusing mcts.py for MuZero: 
compare to mcts with prefect model in AlphaZero, MuZero uses a learned model to do tree search.  As mentioned in Appendix A of paper, there are three places use game rule in AlphaZero while MuZero just replaces with learnt model.

> 1) State transitions. AlphaZero had access to a perfect simulator of the true dynamics process. In contrast, MuZero employs a learned dynamics model within its search. Under this model, each node in the tree is represented by a corresponding hidden state; by providing a hidden state s k−1 and an action a k to the model the search algorithm can transition to a new node s k = g(s k−1 , a k ).
> 2) Actions available. AlphaZero used the set of legal actions obtained from the simulator to mask the prior produced by the network everywhere in the search tree. MuZero only masks legal actions at the root of the search tree where the environment can be queried, but does not perform any masking within the search tree. This is possible because the network rapidly learns not to predict actions that never occur in the trajectories it is trained on.
> 3) Terminal nodes. AlphaZero stopped the search at tree nodes representing terminal states and used the terminal value provided by the simulator instead of the value produced by the network. MuZero does not give special treatment to terminal nodes and always uses the value predicted by the network. Inside the tree, the search can proceed past a terminal node - in this case the network is expected to always predict the same value. This is achieved by treating terminal states as absorbing states during training.

We can do MuZero action mask by inheriting class `mcts.Evaluator`, and we need to solve two other problems:
- If we want to reuse `mcts.py`, maybe we can make a wrapper for Game and game state,  and use transition and reward inference by our network, and use that wrapper as the parameter game in MCTSBot . But the problem is the game object is defined in C++ code,  it may be hard to inherit from `pyspiel.Game` and `pyspiel.State`.
- Or we can define an MCTS base class, and the different variants of MCTS will inherit from it?
- Or the simplest way to rewrite a `MuZeroMCTBot` and have not any depend on other methods.

Is there any advice?

**Comment by lanctot** [comment] 2020-02-19 14:33
Hi @hejujie ! I would think almost surely it would just be easier to make a new MCTS for MuZero (and would clutter `mcts.py` less). @elkhrt, what do you think?

**Comment by elkhrt** [comment] 2020-02-20 19:10
It looks to me as though it should be possible to do this without making
any changes to `mcts.py` - just create a custom wrapper for the State which
holds the root state plus the action history (can be done simply in Python,
no C++ needed, no need to implement the full State API), and a custom
Evaluator which handles such States. And then a new wrapper which at each
turn creates a State wrapper, calls mcts to get an action, and then
executes it on the real environment. If that is possible, then it seems
cleanest and simplest.

However, if that can't be made to work without changing mcts.py, then I
would agree with Marc and prefer a new implementation rather than adding
flags to the existing one.

**Comment by hejujie** [comment] 2020-02-21 17:33
OK, I will divide this work into two steps:
-  the first is to have a draft new implementation based on `mcts.py` and test the correctness in some game, maybe tic_tac_toe as in the implementation of AlphaZero. 
- then do code refactoring and try to adapt it to 'mcts.py' with the custom wrapper.

**Comment by sbodenstein** [comment] 2020-02-28 14:24
@hejujie: I was going to propose implementing this after I had done AlphaZero. But great that you are working on it. Would be happy to help on any parts if you don't have time etc.

**Comment by hejujie** [comment] 2020-03-09 13:03
sorry for the delay,  I'm trying to meet a deadline in the past two weeks, and I restart this work from yesterday.

**Comment by hejujie** [comment] 2020-05-20 10:07
@sbodenstein I am busy in last two months for COVID-19,  the implementation job is always in low priority,  I finished the model part and evaluator part in March, but the code of AlphaZero is being refactored again so it also needs to be refactored (or just rewrite these two parts is better). 
I am afraid that I can't work for it in the next two months, you can do it if you have free time.

**Comment by lanctot** [comment] 2020-06-20 19:16
@hejujie sorry about the clash; we did a fair bit of work on a C++ AlphaZero and this included some necessary refactoring. It was an unfortunate coincidence. We also did not realize how much it would affect your development.

Would still love to see MuZero in the code base but I understand any lack of motivation due to the interruption.

Closing this for now. Feel free to reopen if there are any plans to continue on this.

**Closed** 2020-06-20 19:16 UTC
Labels: contribution welcome
