### ISSUE TITLE
Alpha-rank with empirical agent evaluations in CSV file (dataframe)

### ISSUE THREAD

**Issue by DennisSoemers** [deepmind/open_spiel#106] opened 2019-10-31 09:56 UTC
I've been running experiments with lots of different agents being empirically evaluated in all possible matchups (all possible pairs of agents in 2-player games, all possible triples in 3-player games, etc.), and storing the outcomes of all played games in CSV files.

I'm trying use OpenSpiel's alpha-rank implementation to evaluate these agents, and figured the [from_match_results](https://github.com/deepmind/open_spiel/blob/master/open_spiel/python/egt/heuristic_payoff_table.py#L37) function would be the most convenient approach for converting my CSV data into payoff tables. So I structured my CSV file as described in the comments of that function: a dataframe of two columns, "agents" and "scores", where each of those columns contains a tuple of size n per row for n-player games. Every row corresponds to a single game played between n agents.

I put the code I'm using for this here: https://gist.github.com/DennisSoemers/af5e00c4145ed21cfa99261795d6a113

The comments at the top of the gist also contain a link to an example CSV file with results for a 3-player game. It's about 16MB, if a smaller CSV file would be easier I can prepare one.

For 2-player games, my code appears to work fine and the results I'm getting out of alpha-rank also seem to be reasonable. But with this kind of data for 3-player games, the `alpharank.compute()` call crashes with the following stack-trace:

```
Traceback (most recent call last):
  <snip>
    rhos, rho_m, pi, _, _ = alpharank.compute(payoff_tables, alpha=1e-1)
  File "/home/dennis/Apps/open_spiel/open_spiel/python/egt/alpharank.py", line 636, in compute
    inf_alpha_eps=inf_alpha_eps)
  File "/home/dennis/Apps/open_spiel/open_spiel/python/egt/alpharank.py", line 316, in _get_singlepop_transition_matrix
    use_local_selection_model, payoff_sum)
  File "/home/dennis/Apps/open_spiel/open_spiel/python/egt/alpharank.py", line 150, in _get_rho_sr
    payoff_table, payoffs_are_hpt_format, strat_profile=[r, s], k=0)
  File "/home/dennis/Apps/open_spiel/open_spiel/python/egt/alpharank.py", line 71, in _get_payoff
    payoff_profile = payoff_table_k[tuple(distribution)]
  File "/home/dennis/Apps/open_spiel/open_spiel/python/egt/heuristic_payoff_table.py", line 477, in __getitem__
    return self._payoff_table[distribution]
KeyError: (1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0)
```

Is my CSV file formatted incorrectly? Or am I calling the alpharank code incorrectly? Or is it an issue in the alpharank implementation itself?

I was particularly unsure about line 54 in my gist:

```
payoff_tables = [heuristic_payoff_table.from_match_results(df, all_agents), ]
```

I wrap the output from `heuristic_payoff_table.from_match_results(df, all_agents)` in a single-element list because the subsequent calls seem to expect lists as inputs, but it does seem strange to have to do this to me so I suspect this might be where I'm doing something wrong?

**Comment by DennisSoemers** [comment] 2019-10-31 19:23
@shayegano Yes, I think it works now.

Except, I didn't include self-matchups (i.e. Agent A vs. Agent A) in any of my CSV files, and this is probably the reason why they all crash now due to having some NaN entries (seem to be mostly along a diagonal in every table). I was already re-running some trainings, and planning to re-run my evaluations afterwards... so good to know that I should include some evaluation matches when running them over the weekend!

Follow-up question; can I summarise win percentages / scores obtained in multiple repetitions of the same agents-matchup by averaging them and just having the average results in a single row? That didn't work for me initially, which is why I switched over to having a very long CSV file with the results of every individual evaluation game played, but in hindsight I guess that was just a symptom of my other mistake. If I can average all the results per matchup in a single row, and get a much smaller dataframe, I guess that'd help things to run more quickly.

**Comment by shayegano** [comment] 2019-11-01 10:16
Excellent, happy to hear! Ah yes, the self-matchup results are necessary.

Regarding your question, using the average payoffs should be fine indeed! (Actually, the csv import gist I sent above assumes that, since it doesn't track repeated entries -- I should have mentioned it earlier, so good point).

Hope this helps!

**Comment by DennisSoemers** [comment] 2019-11-06 09:35
@shayegano Sorry for the delay, it took a bit longer than I was hoping for my experiments to start running properly...

I haven't got complete results yet for the 3-player game I was testing, but I do for a few 2-player games. The results I'm getting are rankings / scorings for "Agents" where "Agents" are described as tuples of strategies, exactly like Figure 16 with results for the PSRO poker dataset in the paper.

I was originally kind of looking for results as in Figures 9 and 10 of the paper, with results for the AlphaGo and AlphaZero datasets, where Agents are treated as singular algorithms. But I suppose that in the case of asymmetric games it might be the case that algorithm A is the strongest when playing as Player 1, and a different algorithm B is the strongest when playing as Player 2.

Is this how I should interpret the results I'm currently getting? If I'm getting Agent "(7, 15)" at rank 1, should I interpret this (very roughly) as that Algorithm 7 is the best performing algorithm when playing as the first player (or colour), but Algorithm 15 is the best performing algorithm when playing as the second player (or colour)? And if a single algorithm were the strongest performer across both colours, I would have seen something like (7, 7) at the top rank?

If I know that a game is a symmetric game, would it be an easy change of the code to get back to the AlphaGo/AlphaZero-like results? Though I guess, if we're being really pedantic, we could treat every single one of the 2-player games I'm using as an asymmetric game, since they're all turn-based games which means there could be a minor side advantage for one of the two players...

**Comment by shayegano** [comment] 2019-11-12 21:11
Hey @DennisSoemers, really glad to hear you're seeing reasonable results for 2 player games!

Ah, you're almost there for reproducing Figs 9 and 10 if your game is symmetric. To get plots of that style for a 2-player symmetric game (i.e., each node being a single agent), you should only pass in a list of a single (shared) payoff table, which triggers symmetric alpharank to be run. Maybe a good first step might be to reproduce those symmetric plots for a simple dataset where the output should be intuitive, e.g., try rock-paper-scissors (where the output should be 1/3 1/3 1/3).

For the results you're currently getting, which indeed correspond to asymmetric games, your interpretation is correct in that the output is essentially a joint distribution over the agent profiles. Even in these games, though, if you're seeking something like player-wise agent play probabilities, you should be able to marginalize and get something reasonable. (We tried this approach in some of our recent training approaches that involved asymmetric underlying meta-games, and it worked quite effectively).

I hope this clarifies! Let me know if you have any other questions!

Shayegan

**Comment by lanctot** [comment] 2019-11-12 21:16
Closing as this seems to be resolved. Please re-open if it's not. Thanks!

**Comment by lanctot** [comment] 2019-11-12 21:19
(oops, sorry!)

**Comment by DennisSoemers** [comment] 2019-11-14 13:58
Yes I also got the single-payoff case running, thanks! I'll close the issue then.

**Closed** 2019-11-14 13:59 UTC
