### ISSUE TITLE
ImportError: /xxxx/open_spiel/build/python/pyspiel.so: undefined symbol: PyThread_tss_set

### ISSUE THREAD

**Issue by MakeBestForYou** [deepmind/open_spiel#90] opened 2019-10-06 12:14 UTC
Hello. When I try to run the Build_and_run_tests.sh file, it could Link and built all the target,but there is a Failed in "Performing Test CMAKE_HAVE_LIBC_PTHREAD, Looking for pthread_create in pthreads - not found".And when Test all the target tests, some test occor the massage," ImportError: /XXX/Deepmind/open_spiel/open_spiel/build/python/pyspiel.so: undefined symbol: PyThread_tss_set ". Below is the building message:

+ CXX=g++
+ NPROC=nproc
+ [[ linux-gnu == \d\a\r\w\i\n* ]]
++ nproc
+ MAKE_NUM_PROCS=56
+ let 'TEST_NUM_PROCS=4*56'
++ python3 -c 'import sys; print(sys.version.split(" ")[0])'
+ PYVERSION=3.6.7
+ BUILD_DIR=build
+ mkdir -p build
+ cd build
+ echo 'Building and testing in /XXX/Deepmind/open_spiel/open_spiel/build using '\''python'\'' (version 3.6.7).'
Building and testing in /XXX/Deepmind/open_spiel/open_spiel/build using 'python' (version 3.6.7).
+ cmake -DPython_TARGET_VERSION=3.6.7 -DCMAKE_CXX_COMPILER=g++ ../
-- The C compiler identification is GNU 4.8.5
-- The CXX compiler identification is GNU 7.3.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /public/software/gcc-7.3/bin/g++
-- Check for working CXX compiler: /public/software/gcc-7.3/bin/g++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Failed
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE
-- Found Python3: /***/software/anconda3/lib/libpython3.7m.so (found version "3.7.1") found components:  Development
-- Configuring done
-- Generating done
What should I do for this problem?

**Comment by lanctot** [comment] 2019-10-07 03:59
Hi, based on the output above, it seems like you ran:

```
cmake -DPython_TARGET_VERSION=3.6.7 -DCMAKE_CXX_COMPILER=g++ ../
```

Can you try changing the Python version to remove the .7 ?

```
rm -rf CMakeCache.txt CMakeFiles
CXX=g++ cmake -DPython_TARGET_VERSION=3.6 -DCMAKE_CXX_COMPILER=g++ ../open_spiel
make -j12
ctest -j12
```

**Comment by lanctot** [comment] 2019-10-07 04:01
Hi @MakeBestForYou , is this on MacOSX ?

Either way, you need the `python-dev` packaged.. do you know if your system has it? (Did you run `./install.sh` ?

**Comment by MakeBestForYou** [comment] 2019-10-07 11:23
My system is Centos7, and I can't run the install.sh Because the yum command can't be used,for the system manager have forbidened the command. So I have install the python36_devel manual，but I find does't work, it still use the python37_devel

**Comment by lanctot** [comment] 2019-10-07 15:16
Ah yes, you need to install the equivalent packages (the ones listed here: https://github.com/deepmind/open_spiel/blob/4ecd6161a8a87cda8b77cc0181f5c78d72361508/install.sh#L61) using yum. Did you do that? The packages might be named differently than the ones on Ubuntu/Debian.

**Comment by MakeBestForYou** [comment] 2019-10-09 13:57
Yes, I did. But it had no effect at all. finally I remove the python3.6 and instll a version with python3.7,may be the system can't find the libpython36.so.a file, after this work done, it good working, But have other problem:
1.from graphs import Sonnet, D3Graph, MatplotGraph
ModuleNotFoundError: No module named 'graphs'
2. ./tensorflow/core/kernels/random_op_gpu.h:227] Non-OK-status: CudaLaunchKernel(FillPhiloxRandomKernelLaunch<Distribution>, num_blocks, block_size, 0, d.stream(), gen, data, size, dist) status: Internal: out of memory
Fatal Python error: Aborted


I can't find the module "graphs" in the internet or the open_siple folder.  And the second problem I am very puzzled

**Comment by lanctot** [comment] 2019-10-10 13:17
The first problem seems to be caused by not having sonnet. Did you run the `pip3` command from step 2 of the installation instructions here: https://github.com/deepmind/open_spiel/blob/master/docs/install.md ?

It may also upgrade tensorflow so might affect your second problem too.

**Comment by chrka** [comment] 2019-10-13 17:21
Just had this problem (on macOS) caused by the install script not detecting my Anaconda installation of Python and therefore installing (homebrew) Python 3.7.  (Might be a bug in the install script, at a quick glance it looks as if the check for an existing interpreter has possibly been reversed, but my shell scripting is rusty =)

When building this caused the build to link against Python 3.7 but otherwise using my previous Python 3.6 installation.
Looks as if the same thing might be happening to you:
```
...
echo 'Building and testing in /XXX/Deepmind/open_spiel/open_spiel/build using '''python''' (version 3.6.7).'
...
-- Found Python3: /***/software/anconda3/lib/libpython3.7m.so (found version "3.7.1") found components: Development
...
```
(For me it was easy to fix since I could just remove the homebrew installed Python. After that everything worked fine)

**Comment by scalaboy** [comment] 2019-12-26 15:41
I have get you the same error.
the reason is that I have install anacond3(python3.7),while I conda create -n tfgpu python=3.6
and install the open_spiel。so pyspile is install by python3.7.which is in you log as :

Found Python3: /***/software/anconda3/lib/libpython3.7m.so (found version "3.7.1") found

but you active python is :

echo 'Building and testing in /XXX/Deepmind/open_spiel/open_spiel/build using '''python''' (version 3.6.7).'


my solutions is as follows
reinstall anaconda3(python3.6).
and all is ok

**Comment by lanctot** [comment] 2020-02-25 15:09
Hi @MakeBestForYou ,

Was this ever resolved? Did the fixes other people suggest work for you?

Your last reply was in October, so I am inclined to close this issue.

**Closed** 2020-02-26 20:17 UTC

**Comment by adityauser** [comment] 2020-04-17 07:51
@scalaboy @lanctot do you have any other alternate solution to resolve this issue, without reinstalling anaconda3(python3.6)?
I'm getting this issue in Ubuntu 18.04, anaconda3(python 3.7).
For installation, I'm creating a new environment using the command` conda create -n OpenSpiel python=3.6`.
There should be some way to resolve this issue without downgrading anaconda3(python3.7) to anaconda3(python3.6).

**Comment by lanctot** [comment] 2020-04-17 14:27
I have never used anaconda but I know we have managed to get it working with 3.7. If you follow the manual install using PYTHON_TARGET_VERSION=3.7, does it not work?

**Comment by adityauser** [comment] 2020-04-17 19:52
Yeah it worked but now I'm failing `Test #141: run_python_test` with error `ModuleNotFoundError: No module named 'absl'`
I did following steps:
Creating enviroment:
```
conda create -n OpenSpiel python=3.7
conda activate OpenSpiel
```
Installation steps:
```
./install.sh
python -m pip install .
mkdir build
cd build
CXX=clang++ cmake -DPython_TARGET_VERSION=3.7 -DCMAKE_CXX_COMPILER=${CXX} ../open_spiel
make -j$(nproc)
ctest -j$(nproc)
```

**Comment by lanctot** [comment] 2020-04-17 20:51
Ok great now you need to install the pip dependencies, see this page: https://github.com/deepmind/open_spiel/blob/master/docs/install.md

**Comment by adityauser** [comment] 2020-04-18 10:27
Thanks for all your help @lanctot .
