### ISSUE TITLE
Build failure in install_open_spiel.ipynb colab

### ISSUE THREAD

**Issue by akileshbadrinaaraayanan** [deepmind/open_spiel#320] opened 2020-08-18 16:13 UTC
Hello,

The "Build Open Spiel" sub-section inside the Colab fails since some time with the below error:

```[  4%] Building CXX object abseil-cpp/absl/time/CMakeFiles/absl_time_zone.dir/internal/cctz/src/time_zone_impl.cc.o
[  4%] Building CXX object abseil-cpp/absl/time/CMakeFiles/absl_time_zone.dir/internal/cctz/src/time_zone_info.cc.o
[  4%] Building CXX object abseil-cpp/absl/time/CMakeFiles/absl_time_zone.dir/internal/cctz/src/time_zone_libc.cc.o
[  4%] Building CXX object abseil-cpp/absl/time/CMakeFiles/absl_time_zone.dir/internal/cctz/src/time_zone_lookup.cc.o
[  5%] Building CXX object abseil-cpp/absl/time/CMakeFiles/absl_time_zone.dir/internal/cctz/src/time_zone_posix.cc.o
[  5%] Building CXX object abseil-cpp/absl/time/CMakeFiles/absl_time_zone.dir/internal/cctz/src/zone_info_source.cc.o
[  5%] Linking CXX static library libabsl_time_zone.a
[  5%] Built target absl_time_zone
Makefile:94: recipe for target 'all' failed
make: *** [all] Error 2``` 


Do you have suggestions on how to fix this?

**Comment by lanctot** [comment] 2020-08-18 17:31
Hi @akileshbadrinaaraayanan , thanks for letting us know. 

I would need to see more than this, though-- seems like the actual cause is getting cut off. Do you still have it?

We've have some problems with the build over the past few days from a few bad updates, which are now fixed. When did you try? I suspect this is almost certainly the cause.. you might need to pull from master again (maybe via reloading the colab?), but I can say for sure if you can post the real error message (if you can do the equivalent of "scrolling up").

**Comment by akileshbadrinaaraayanan** [comment] 2020-08-18 17:42
Hi @lanctot , thank you very much for your prompt response. 

Sure, that makes total sense (my bad!). I'm posting the complete message. Below is the log from my try at the moment. 

```/usr/local/open_spiel/build
-- The C compiler identification is GNU 7.5.0
-- The CXX compiler identification is Clang 6.0.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/clang++
-- Check for working CXX compiler: /usr/bin/clang++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
Current build type is: Testing
BUILD_WITH_ACPC not set. Defaults to OFF
BUILD_WITH_ACPC: OFF 
BUILD_WITH_EIGEN not set. Defaults to OFF
BUILD_WITH_EIGEN: OFF 
BUILD_WITH_HANABI: ON 
BUILD_WITH_JULIA not set. Defaults to OFF
BUILD_WITH_JULIA: OFF 
BUILD_WITH_LIBTORCH not set. Defaults to OFF
BUILD_WITH_LIBTORCH: OFF 
BUILD_WITH_PUBLIC_STATES not set. Defaults to OFF
BUILD_WITH_PUBLIC_STATES: OFF 
BUILD_WITH_PYTHON not set. Defaults to ON
BUILD_WITH_PYTHON: ON 
BUILD_WITH_XINXIN not set. Defaults to OFF
BUILD_WITH_XINXIN: OFF 
BUILD_WITH_ROSHAMBO not set. Defaults to OFF
BUILD_WITH_ROSHAMBO: OFF 
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Looking for pthread_create
-- Looking for pthread_create - not found
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE  
-- Found Python3: /usr/bin/python3.6 (found version "3.6.9") found components:  Interpreter Development 
-- Configuring done
-- Generating done
-- Build files have been written to: /usr/local/open_spiel/build
Scanning dependencies of target open_spiel_core
Scanning dependencies of target absl_log_severity
[  0%] Building CXX object abseil-cpp/absl/base/CMakeFiles/absl_log_severity.dir/log_severity.cc.o
[  0%] Building CXX object CMakeFiles/open_spiel_core.dir/canonical_game_strings.cc.o
[  1%] Linking CXX static library libabsl_log_severity.a
[  1%] Built target absl_log_severity
[  2%] Building CXX object CMakeFiles/open_spiel_core.dir/fog/observation_history.cc.o
[  2%] Building CXX object CMakeFiles/open_spiel_core.dir/game_parameters.cc.o
In file included from /usr/local/open_spiel/open_spiel/fog/observation_history.cc:15:
In file included from /usr/local/open_spiel/open_spiel/../open_spiel/fog/observation_history.h:24:
In file included from /usr/local/open_spiel/open_spiel/../open_spiel/spiel.h:36:
/usr/local/open_spiel/open_spiel/../open_spiel/game_parameters.h:117:7: error: explicit specialization of 'value' in class scope
  int value() const {
      ^
/usr/local/open_spiel/open_spiel/../open_spiel/game_parameters.h:121:10: error: explicit specialization of 'value' in class scope
  double value() const {
         ^
/usr/local/open_spiel/open_spiel/../open_spiel/game_parameters.h:125:22: error: explicit specialization of 'value' in class scope
  const std::string& value() const {
                     ^
/usr/local/open_spiel/open_spiel/../open_spiel/game_parameters.h:129:15: error: explicit specialization of 'value' in class scope
  std::string value() const {
              ^
/usr/local/open_spiel/open_spiel/../open_spiel/game_parameters.h:133:8: error: explicit specialization of 'value' in class scope
  bool value() const {
       ^
/usr/local/open_spiel/open_spiel/../open_spiel/game_parameters.h:137:47: error: explicit specialization of 'value' in class scope
  const std::map<std::string, GameParameter>& value() const {
                                              ^
/usr/local/open_spiel/open_spiel/../open_spiel/game_parameters.h:141:40: error: explicit specialization of 'value' in class scope
  std::map<std::string, GameParameter> value() const {
                                       ^
In file included from /usr/local/open_spiel/open_spiel/game_parameters.cc:15:
/usr/local/open_spiel/open_spiel/../open_spiel/game_parameters.h:117:7: error: explicit specialization of 'value' in class scope
  int value() const {
      ^
/usr/local/open_spiel/open_spiel/../open_spiel/game_parameters.h:121:10: error: explicit specialization of 'value' in class scope
  double value() const {
         ^
/usr/local/open_spiel/open_spiel/../open_spiel/game_parameters.h:125:22: error: explicit specialization of 'value' in class scope
  const std::string& value() const {
                     ^
/usr/local/open_spiel/open_spiel/../open_spiel/game_parameters.h:129:15: error: explicit specialization of 'value' in class scope
  std::string value() const {
              ^
/usr/local/open_spiel/open_spiel/../open_spiel/game_parameters.h:133:8: error: explicit specialization of 'value' in class scope
  bool value() const {
       ^
/usr/local/open_spiel/open_spiel/../open_spiel/game_parameters.h:137:47: error: explicit specialization of 'value' in class scope
  const std::map<std::string, GameParameter>& value() const {
                                              ^
/usr/local/open_spiel/open_spiel/../open_spiel/game_parameters.h:141:40: error: explicit specialization of 'value' in class scope
  std::map<std::string, GameParameter> value() const {
                                       ^
7 errors generated.
CMakeFiles/open_spiel_core.dir/build.make:75: recipe for target 'CMakeFiles/open_spiel_core.dir/fog/observation_history.cc.o' failed
make[2]: *** [CMakeFiles/open_spiel_core.dir/fog/observation_history.cc.o] Error 1
make[2]: *** Waiting for unfinished jobs....
Scanning dependencies of target absl_exponential_biased
[  2%] Building CXX object abseil-cpp/absl/base/CMakeFiles/absl_exponential_biased.dir/internal/exponential_biased.cc.o
7 errors generated.
CMakeFiles/open_spiel_core.dir/build.make:88: recipe for target 'CMakeFiles/open_spiel_core.dir/game_parameters.cc.o' failed
make[2]: *** [CMakeFiles/open_spiel_core.dir/game_parameters.cc.o] Error 1
CMakeFiles/Makefile2:72: recipe for target 'CMakeFiles/open_spiel_core.dir/all' failed
make[1]: *** [CMakeFiles/open_spiel_core.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
[  2%] Linking CXX static library libabsl_exponential_biased.a
[  2%] Built target absl_exponential_biased
Makefile:94: recipe for target 'all' failed
make: *** [all] Error 2```

**Comment by lanctot** [comment] 2020-08-18 18:08
Hmm, ok that seems like a deeper issue to me. Odd, it compiles fine internally and it just passed the Travis-CI tests an hour ago. There must be a discrepancy in the build environment on the colab systems.

@elkhrt @michalsustr @dhennes , any ideas what could be the cause?

**Comment by sullins2** [comment] 2020-08-19 15:36
I have the same error. It was working two days ago so I suspect it is a recent change that did it.

**Comment by lanctot** [comment] 2020-08-19 15:54
We think we know the cause. The colab hosts have an old version of clang so we have been unable to reproduce on our end. But we are looking into it, though, and will try to get it fixed as soon as we can.

**Comment by dhennes** [comment] 2020-08-20 12:09
Hi @akileshbadrinaaraayanan, @sullins2 
Until this is fixed, you can get OpenSpiel to build in Colab by installing a recent version of clang:
Just add the following to a cell of your notebook and run it before you build:
```
!apt-get install clang-9
```
You also need to pass the correct flag to cmake in the "Build `open_spiel`" section (specially, change the line that starts with `CXX=clang++ ...`):
```
!cmake -DPython_TARGET_VERSION=3.6 -DCMAKE_CXX_COMPILER=`which clang++-9` ../open_spiel
```

**Comment by sullins2** [comment] 2020-08-20 13:29
Thanks @dhennes

**Comment by elkhrt** [comment] 2020-08-20 13:54
Fix incoming.

**Closed by elkhrt** 2020-08-20 13:54 UTC
