### ISSUE TITLE
Issue with spiel_move_to_checker_moves (Backgammon)

### ISSUE THREAD

**Issue by RjVicks** [deepmind/open_spiel#561] opened 2021-04-16 11:10 UTC
Hello again,

I have found an issue with the "state.spiel_move_to_checker_moves" function in backgammon.

The third item in the "checker_moves" array, (which is the return of "state.spiel_move_to_checker_moves"), flags if an opponent's checker was 'hit' i.e. placed on the bar.

This boolean is always displaying false even when an opponent is hit. I have attached an image.

**Comment by RjVicks** [comment] 2021-04-16 11:10
![issue-with-checker-move](https://user-images.githubusercontent.com/26366162/115016297-c6b13d80-9eac-11eb-9558-9b46b941a113.png)

**Comment by RjVicks** [comment] 2021-04-16 11:11
Consider where the terminal displays:

 Checker moves:
pos 3, num 1, hit? False
pos 0, num 6, hit? False

**Comment by RjVicks** [comment] 2021-04-16 11:17
As aside, please can I ask for your advice with something.

Please can you inform me on how I can get the number of checkers at a given point?
Is it possible to retrieve this information from the api?

For example, I would like to know how many checkers are at point number 4. A function of the sorts:

state.get_num_checkers_at_point(point_index=4)

**Comment by lanctot** [comment] 2021-04-16 12:38
I just took a look at the code, the missing hit info is actually a bug. I'll fix it today, add a test, and the fix should be merged in our next update (Monday). Thanks for finding & reporting this.

As for more inspection function: I wrote the games_backgammon.cc file specifically for that. It doesn't contain the one you're looking for, but you can quite easily add all the ones you need (they are one-line wrappers to the C++ state's object). I will add this specific one in the same commit as the bug fix so you can see an example of how to add one.

**Comment by lanctot** [comment] 2021-04-17 09:47
I take it back: it is not a bug. Some internal logic relies on that function to not contain hit information, but I have added an extra function to augment them with the hit information with an example. Will be included in Monday's update.

**Comment by RjVicks** [comment] 2021-04-18 15:36
Ah, that's great. Thank you so much :)

**Closed** 2021-04-19 09:16 UTC
