### ISSUE TITLE
Unable to build and run tests - CMAKE_HAVE_LIBC_PTHREAD

### ISSUE THREAD

**Issue by skifpankov** [deepmind/open_spiel#11] opened 2019-08-28 19:46 UTC
**environment:**
system: Ubuntu 18.04.3 LST
cmake: 3.15.2
compiler: gcc (Ubuntu 6.5.0-2ubuntu1~18.04) 6.5.0 20181026

I am unable to build and run tests (the following was run within the activated virtual environment, as specified in the installation instructions):

~/github/open_spiel/build$ CXX=g++ cmake -DPython_TARGET_VERSION=3.6 -DCMAKE_CXX_COMPILER=${CXX} ../open_spiel
-- The C compiler identification is GNU 7.4.0
-- The CXX compiler identification is GNU 6.5.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/local/cuda-9.0/bin/g++
-- Check for working CXX compiler: /usr/local/cuda-9.0/bin/g++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Failed
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE  
-- Found Python3: /usr/lib/x86_64-linux-gnu/libpython3.6m.so (found version "3.6.8") found components:  Development 
-- Configuring done
You have changed variables that require your cache to be deleted.
Configure will be re-run and you may have to reset some variables.
The following variables have changed:
CMAKE_CXX_COMPILER= /usr/local/cuda-9.0/bin/g++

-- The C compiler identification is GNU 7.4.0
-- The CXX compiler identification is GNU 6.5.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/local/cuda-9.0/bin/g++
-- Check for working CXX compiler: /usr/local/cuda-9.0/bin/g++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Failed
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE  
CMake Error at python/CMakeLists.txt:1 (if):
  if given arguments:

    "STREQUAL" ""

  Unknown arguments specified

-- Configuring incomplete, errors occurred!
See also "/home/skif/github/open_spiel/build/CMakeFiles/CMakeOutput.log".
See also "/home/skif/github/open_spiel/build/CMakeFiles/CMakeError.log".
You have changed variables that require your cache to be deleted.
Configure will be re-run and you may have to reset some variables.
The following variables have changed:
CMAKE_CXX_COMPILER= /usr/local/cuda-9.0/bin/g++

CMAKE_HAVE_LIBC_PTHREAD is causing an issue - I am not entirely sure how to resolve it.

Any suggestions would be most welcome. Apologies in advance if it's a trivial issue

**Comment by lanctot** [comment] 2019-08-28 23:30
Could you try hard coding the absolute path to your compiler?

1. In build, rm -rf CMakeCache.txt CMakeFiles/ # remove cmake meta info
2. CXX= /usr/local/cuda-9.0/bin/g++ cmake -DPython_TARGET_VERSION=3.6 -DCMAKE_CXX_COMPILER=${CXX} ../open_spiel

If that fails then my guess is that it is related to the fact that you are using a custom cuda-enabled g++ which might be missing standard pthread support? 

(This guess is based only on the path to your g++)

**Comment by axissun** [comment] 2019-08-29 01:45
@skifpankov 
I just solve the problem by modify the  python/CMakeLists.txt line 1：
- if(${Python_TARGET_VERSION} STREQUAL "")
+ if(True)

**Comment by bradhowes** [comment] 2019-08-29 10:21
IMO, the expression `if(${Python_TARGET_VERSION} STREQUAL "")` can/should be rewritten as `if(Python_TARGET_VERSION STREQUALS "")` which will solve the issue when `Python_TARGET_VERSION` is undefined.

**Comment by lanctot** [comment] 2019-08-30 12:34
Thanks @bradhowes, that is a good suggestion, we will look into making that change!

**Comment by lanctot** [comment] 2019-08-30 12:36
@skifpankov, were you able to resolve your build issue?

**Comment by skifpankov** [comment] 2019-09-01 08:38
Hi @lanctot, apologies for the delay.

I have tried all 3 suggestions, and I am afraid none of them worked.

- hard coding the absolute path to your compiler **only**

-- The C compiler identification is GNU 7.4.0
-- The CXX compiler identification is GNU 6.5.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/local/cuda-9.0/bin/g++
-- Check for working CXX compiler: /usr/local/cuda-9.0/bin/g++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Failed
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE  
-- Found Python3: /usr/lib/x86_64-linux-gnu/libpython3.6m.so (found version "3.6.8") found components:  Development 
-- Configuring done
You have changed variables that require your cache to be deleted.
Configure will be re-run and you may have to reset some variables.
The following variables have changed:
CMAKE_CXX_COMPILER= /usr/local/cuda-9.0/bin/g++

-- The C compiler identification is GNU 7.4.0
-- The CXX compiler identification is GNU 6.5.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/local/cuda-9.0/bin/g++
-- Check for working CXX compiler: /usr/local/cuda-9.0/bin/g++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Failed
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE  
CMake Error at python/CMakeLists.txt:1 (if):
  if given arguments:

    "STREQUAL" ""

  Unknown arguments specified


-- Configuring incomplete, errors occurred!
See also "/home/skif/github/open_spiel/build/CMakeFiles/CMakeOutput.log".
See also "/home/skif/github/open_spiel/build/CMakeFiles/CMakeError.log".
You have changed variables that require your cache to be deleted.
Configure will be re-run and you may have to reset some variables.
The following variables have changed:
CMAKE_CXX_COMPILER= /usr/local/cuda-9.0/bin/g++

- hard coding the absolute path to your compiler **and** replacing `if(${Python_TARGET_VERSION} STREQUAL "")` with `if(Python_TARGET_VERSION STREQUALS "")` in python/CMakeLists.txt

-- The C compiler identification is GNU 7.4.0
-- The CXX compiler identification is GNU 6.5.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/local/cuda-9.0/bin/g++
-- Check for working CXX compiler: /usr/local/cuda-9.0/bin/g++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Failed
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE  
CMake Error at python/CMakeLists.txt:1 (if):
  if given arguments:

    "Python_TARGET_VERSION" "STREQUALS" ""

  Unknown arguments specified


-- Configuring incomplete, errors occurred!
See also "/home/skif/github/open_spiel/build/CMakeFiles/CMakeOutput.log".
See also "/home/skif/github/open_spiel/build/CMakeFiles/CMakeError.log".
You have changed variables that require your cache to be deleted.
Configure will be re-run and you may have to reset some variables.
The following variables have changed:
CMAKE_CXX_COMPILER= /usr/local/cuda-9.0/bin/g++

-- Generating done
CMake Generate step failed.  Build files cannot be regenerated correctly.

- **only** replacing `if(${Python_TARGET_VERSION} STREQUAL "")` with `if(Python_TARGET_VERSION STREQUALS "")` in python/CMakeLists.txt

-- The C compiler identification is GNU 7.4.0
-- The CXX compiler identification is GNU 6.5.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/local/cuda-9.0/bin/g++
-- Check for working CXX compiler: /usr/local/cuda-9.0/bin/g++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Failed
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE  
CMake Error at python/CMakeLists.txt:1 (if):
  if given arguments:

    "Python_TARGET_VERSION" "STREQUALS" ""

  Unknown arguments specified


-- Configuring incomplete, errors occurred!
See also "/home/skif/github/open_spiel/build/CMakeFiles/CMakeOutput.log".
See also "/home/skif/github/open_spiel/build/CMakeFiles/CMakeError.log".
You have changed variables that require your cache to be deleted.
Configure will be re-run and you may have to reset some variables.
The following variables have changed:
CMAKE_CXX_COMPILER= /usr/local/cuda-9.0/bin/g++

- replacing `if(${Python_TARGET_VERSION} STREQUAL "")` with `if(True)`

Produces an infinite loop of:
-- The C compiler identification is GNU 7.4.0
-- The CXX compiler identification is GNU 6.5.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/local/cuda-9.0/bin/g++
^X-- Check for working CXX compiler: /usr/local/cuda-9.0/bin/g++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Failed
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE  
-- Found Python: /usr/lib/x86_64-linux-gnu/libpython3.6m.so (found version "3.6.8") found components:  Development 
-- Configuring done
You have changed variables that require your cache to be deleted.
Configure will be re-run and you may have to reset some variables.
The following variables have changed:
CMAKE_CXX_COMPILER= /usr/local/cuda-9.0/bin/g++

I guess it all points to the g++ compiler incompatibility.

Would you be happy to recommend a version of g++ which should I be compiling against?

**Comment by skifpankov** [comment] 2019-09-01 08:50
**UPDATE**

Building against Ubuntu's default g++ (in /usr/bin/) worked (all tests passed), however there was still a problem with CMAKE_HAVE_LIBC_PTHREAD when I run `CXX=/usr/bin/g++ cmake -DPython_TARGET_VERSION=3.6 -DCMAKE_CXX_COMPILER=${CXX} ../open_spiel` :

-- The C compiler identification is GNU 7.4.0
-- The CXX compiler identification is GNU 7.4.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/g++
-- Check for working CXX compiler: /usr/bin/g++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Failed
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE  
-- Found Python3: /usr/lib/x86_64-linux-gnu/libpython3.6m.so (found version "3.6.8") found components:  Development 
-- Configuring done
-- Generating done
-- Build files have been written to: /home/skif/github/open_spiel/build

How much of a problem is it? Is using a different version of g++ solve it?

**Comment by lanctot** [comment] 2019-09-20 21:20
Odd, had not seen that before and I have only used the default compilers.

If the tests are passing then it sounds like everything is working so I will close this one. Feel free to reopen if there is any indication of problems caused by this.

**Closed by lanctot** 2019-09-20 21:20 UTC
