### ISSUE TITLE
More Oracles for PSRO

### ISSUE THREAD

**Issue by ying-wen** [deepmind/open_spiel#103] opened 2019-10-25 13:47 UTC
Currently, there is only a simple oracle Evolutionary Strategy implemented in ```open_spiel/python/algorithms/psro_variations/optimization_oracle.py```.

To reproduce the results in https://arxiv.org/pdf/1711.00832.pdf (Reactor), https://arxiv.org/pdf/1909.12823.pdf (PBR), etc, more oracles (e.g., deep reinforcement learning) are required to expand a new policy over mixed meta policies.

Let me know if I have missed somethings/oracles that already implemented in the project.

**Comment by lanctot** [comment] 2019-10-25 14:04
Hi @ying-wen , you have not missed anything; we did manage to reproduce the original PSRO internally (for a uniform meta-strategy), but we had to release it only partially complete because we were too busy to get the last two bits in at the time: (i) a policy aggregator, to turn the meta-strategy over oracles into a behavioral strategy, and (ii) deep RL based oracles.

@PaulFMMuller added the policy aggregator a few weeks ago (see `python/algorithms/policy_aggregator.py`). We do not have an implementation of Reactor in the code base but we hope to have a DQN-based best response oracle. We are working on it, but I can't promise a timeline. I would also encourage you to try doing it and turning it into a pull request (the DQN we have should already support the case of playing against a fixed opponent -- so it's just a matter of sampling one of the opponents' oracles at the start of each episode).

**Comment by PaulFMMuller** [comment] 2019-10-27 12:24
Hi @ying-wen, thank you for your interest in PBR and our papers !
I second @lanctot for the reproduction of the Leduc, Kuhn and other Openspiel-based results ; only a DQN oracle is missing for that :)

Regarding the reproduction of the PBR results, two big pieces are missing : a PBR best-responder, and a random-yet-interesting-game generator. These two have been created for the paper, and we should therefore be able to include them in a future release.

**Comment by lanctot** [comment] 2019-11-12 21:16
Closing this for now but will come back to reply when we add more PSRO oracles!

**Closed by lanctot** 2019-11-12 21:16 UTC
Labels: contribution welcome
